# Generated by Django 5.1.15 on 2026-05-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_dailyprogress_matn_memorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='book_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='english_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='learned_something',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='learning_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='reading_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
